# Generated by Django 5.1.6 on 2025-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('adrees', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
